### PR TITLE
Refactored entity objects and more

### PR DESCRIPTION
**Pull request by eladperlman**
Refactored entity objects to not communicate with the database and added the calls to the appropriate interactors. As well as refined some of the buy and sell interactors and their tests to store unique test usernames as constants instead of magic values.

### CODE REVIEW

**Review by jackzxliu — APPROVED** [review]
reviewd

**Review by Yoda476592 — DISMISSED** [review]
Looks Good! Need this to work on other parts of the project.

**Review by noel-toms — APPROVED** [review]
Need this merged asap

**Review by Spaghetti-12 — DISMISSED** [review]

**Review by inaam10-tech — APPROVED** [review]
Seems good

**Review by Spaghetti-12 — APPROVED** [review]

**Review by benmarlow — APPROVED** [review]
All looks good. Approve

**Pull request merged**
