### PR TITLE
Update Documentation

### PR DESCRIPTION
**Pull request by inaam10-tech**
Updated Documentation on various files and fixed a few extra IntelliJ warnings.

### CODE REVIEW

**Review by Peaceful36 — DISMISSED** [review]
Nice additions on the javadocs

**Review by Peaceful36 — DISMISSED** [review]

**Review by noel-toms — APPROVED** [review]
Nice work adding more documentation

**Review by benmarlow — APPROVED** [review]
Good work on the javadocs, much needed improvements.

**Review by Peaceful36 — APPROVED** [review]
Nice addition for docs

**Review by eladperlman — APPROVED** [review]
Good job!

**Pull request merged**
