### PR TITLE
feature 3 portfolio creation completed

### PR DESCRIPTION
**Pull request by jackzxliu**
- made a change to OuterLayerFactory which needs to be reviewed
- made a new GUI for portfolio creation page (functional but looks ugly)
- implemented controller, interactor and presenter for portfoliocreation
- changed the name of createPortfolioPresenter to UserPresenter and made a new createPortfolioPresenter that corresponds to the CreatePortfolioGUI instead of UserGUI

### CODE REVIEW

**Review by eladperlman — DISMISSED** [review]
All looks good!

**Review by Spaghetti-12 — APPROVED** [review]
Looks good!

**Review by eladperlman — APPROVED** [review]
Looks good!

**Comment by Rohh1** [comment]
Looks good!

**Review by Rohh1 — APPROVED** [review]
Looks good!

**Pull request merged**
