### PR TITLE
Changed file names and packaging structure to fit with TA's comments

### PR DESCRIPTION
**Pull request by eladperlman**
Changed file names and packaging structure to fit with TA's comments

### CODE REVIEW

**Review by Spaghetti-12 — DISMISSED** [review]
Good stuff!

**Review by benmarlow — DISMISSED** [review]
Nice changes. Approved

**Review by jackzxliu — APPROVED** [review]
approval

**Review by noel-toms — APPROVED** [review]
Updates look good

**Review by benmarlow — APPROVED** [review]
Approved. Nice job

**Review by Spaghetti-12 — APPROVED** [review]

**Review by inaam10-tech — APPROVED** [review]
Good fix

**Review by noel-toms — APPROVED** [review]
Looks Goof

**Pull request merged**
