### PR TITLE
Added documentation to all files I have worked on

### PR DESCRIPTION
**Pull request by eladperlman**
Added documentation to entities, entity database classes, and user login use case. Also added all finished GUI images and description of user login to the read me file

### CODE REVIEW

**Review by benmarlow — DISMISSED** [review]
Great work, thanks Elad.

**Review by Spaghetti-12 — APPROVED** [review]
Good stuff!

**Review by inaam10-tech — APPROVED** [review]
Seems good

**Review by Peaceful36 — APPROVED** [review]
good stuffs

**Review by noel-toms — APPROVED** [review]
looks good. The project is becoming more polished

**Pull request merged**
