### PR TITLE
Fixed issue where leaderboard was not getting current values from the stock API

### PR DESCRIPTION
**Pull request by benmarlow**

### CODE REVIEW

**Review by Spaghetti-12 — DISMISSED** [review]
good catch!

**Review by inaam10-tech — APPROVED** [review]
nice job implementing the fix

**Review by jackzxliu — APPROVED** [review]
approval

**Review by noel-toms — APPROVED** [review]
Looks good now after the changes

**Review by inaam10-tech — APPROVED** [review]
Approved. Good fix

**Pull request merged**
