### PR TITLE
Adding Leaderboard into Main

### PR DESCRIPTION
**Pull request by benmarlow**
This is still experiencing some issues but adds partial functionality to the leaderboard in the form of a button which takes the user from their home screen to the Leaderboard GUI. The GUI is not properly showcasing top users right now, and will require full implementation of the PortfolioGUI and some tweaking in order to be fully operational. 

Also adds a button to the Portfolio GUI which allows the user to turn this portfolio into their "competitive portfolio". Again, functionality is limited, but the button is there. If anyone has input on why the button does not convert the portfolio to the user's competitive portfolio, please let me know as I am confused.

Added javadoc to methods written for the leaderboard use case.

Added a few test cases in LeaderboardTest.

### CODE REVIEW

**Review by noel-toms — COMMENTED** [review]
I think some more tests that include the database should be added as the leaderboard gets the users from the database. You can add some test tables with values in the database to test different cases. For example, 2 users with the same portfolio value, how are they ranked?

**Comment by inaam10-tech** [comment]
I feel like everything looks good, I think the main thing is that in your tests, 

"iEntityDBGateway dbGateway = OuterLayerFactory.instance.getEntityDSGateway();"
This may cause an error in main branch.

**Review by Spaghetti-12 — COMMENTED** [review]
Looks good to me. Good stuff!

**Review by Spaghetti-12 — DISMISSED** [review]

**Comment by benmarlow** [comment]
> I feel like everything looks good, I think the main thing is that in your tests,
> 
> "iEntityDBGateway dbGateway = OuterLayerFactory.instance.getEntityDSGateway();" This may cause an error in main branch.

**Comment by benmarlow** [comment]
Sorry, I am a bit confused because none of the tests appear to be running. All of the stuff in this PR remain the same as of right now, but I can write more for the time being

**Review by eladperlman — APPROVED** [review]
Looks good, please try to merge this ASAP

**Review by jackzxliu — APPROVED** [review]
looks good

**Review by Peaceful36 — APPROVED** [review]
Good stuffs but I think you need to add some tests for your case

**Pull request merged**
