### PR TITLE
Fixed app crashing when user buys or sells a stock they don't own as …

### PR DESCRIPTION
**Pull request by eladperlman**
…well as made the app pull the portfolio's stocks most recent prices from the API instead of the entity database

### CODE REVIEW

**Review by noel-toms — COMMENTED** [review]
Are the changes to the sell stock similar to the other pull request?https://github.com/CSC207-2022F-UofT/course-project-Team-Stonks/pull/57 - PR 57

**Comment by eladperlman** [comment]
> Are the changes to the sell stock similar to the other pull request?#57 - PR 57

yes, the other PR should be closed since this takes care of it

**Comment by noel-toms** [comment]
> > Are the changes to the sell stock similar to the other pull request?#57 - PR 57
> 
> yes, the other PR should be closed since this takes care of it

Could you clarify how the new changes avoid the issue of selling stock that the user doesn't own? I'm wondering if the previous implementation where the sell button is disabled is an easier solution (The solution in the closed PR).

**Review by Peaceful36 — APPROVED** [review]
Looks good

**Review by Spaghetti-12 — DISMISSED** [review]
looks good!

**Review by Peaceful36 — APPROVED** [review]

**Review by noel-toms — APPROVED** [review]
Looks good now

**Review by Spaghetti-12 — APPROVED** [review]
looks good!

**Pull request merged**
