### PR TITLE
Bug Fixed in Testing

### PR DESCRIPTION
**Pull request by inaam10-tech**
FIxed a small bug with dates.

### CODE REVIEW

**Comment by benmarlow** [comment]
Perfect, thanks Inaam

**Comment by benmarlow** [comment]
Looks good to me.

**Review by Spaghetti-12 — APPROVED** [review]
Looks good to me.

**Review by noel-toms — APPROVED** [review]
Seems Good

**Review by eladperlman — APPROVED** [review]
Looks good

**Pull request merged**
