### PR TITLE
6 feature 6 sell stock

### PR DESCRIPTION
**Pull request by noel-toms**
Fixed the issue of missing JLabel. The JLabel was created in the .form file but never declared in the java file. This caused an error and prevented the program from running.

### CODE REVIEW

**Comment by noel-toms** [comment]
New Change: I switched the order of the parameters in register tests. The order is expected and then actual values, however, it was the other way around before. This just helps for testing purposes, as otherwise if something fails, it's going to show the wrong expected value.

**Review by benmarlow — DISMISSED** [review]
Looks perfect, this should fix that issue. Approved!

**Review by eladperlman — APPROVED** [review]
Looks good!

**Comment by Peaceful36** [comment]
Just limit the number of decimals being displayed in Portfolio GUI and add stuffs to documentation

**Review by inaam10-tech — APPROVED** [review]
seems good

**Review by eladperlman — APPROVED** [review]
Looks good!

**Pull request merged**
