### PR TITLE
Testing + Javadocs with revisions

### PR DESCRIPTION
**Pull request by inaam10-tech**
Finished the Testing accounting for different errors and considered reviews in previous PR. This should any issues.

### CODE REVIEW

**Comment by inaam10-tech** [comment]
Completed. Let me know if I missed anything.

**Review by Rohh1 — APPROVED** [review]
Great job on starting the documentation for your functions and adding in some test cases. The test cases seem to cover a variety of possible scenarios.

**Review by Rohh1 — APPROVED** [review]
All looks good!

**Review by noel-toms — APPROVED** [review]
Looks Good. Seems like you covered the most important test cases

**Review by Peaceful36 — APPROVED** [review]
I think you did a good job reviewing the previous comments and adjusting your test cases to match the necessary conditions needed for testing.

**Pull request merged**
